# Generated by Django 5.2.5 on 2025-08-13 18:25

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthentry",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="health_attachments/",
                validators=[
                    authentication.validators.validate_file_extension,
                    authentication.validators.validate_file_size,
                ],
            ),
        ),
    ]
